<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Name' => 'Имя',
    'Title' => 'Название',
    'Comment' => 'Комментарий',
    'Start the working day' => 'Начать рабочий день',
    'Finish the working day' => 'Закончить рабочий день',
    'Break' => 'Перерыв',
    'Time Tracking' => 'Учет рабочего времени',
    'Time' => 'Время',
    'Update time' => 'Время обновления',
    'The start of the working day is marked' => 'Начало рабочего дня отмечено',
    'The end of the working day is marked' => 'Завершение рабочего дня отмечено',
    'The break of the working day is marked' => 'Отмечен перерыв в рабочем дне',
    'Activity' => 'Активность',
    'Activity added' => 'Активность добавлена',
    'The begining of the work day' => 'Начало рабочего дня',
    'End of the working day' => 'Завершение рабочего дня',
    'You have completed your working day.' => 'Вы завершили рабочий день.',
    'Add Activity' => 'Добавить активность',
    "You've already finished your work day!" => 'Вы уже закончили рабочий день!',
    'Role' => 'Роль',
    'Activities' => 'Активности',
    'Position' => 'Позиция',
    'Role Activities' => 'Активности ролей',
    'Add Activity for Role' => 'Добавить активность для роли',
    'Update Role Activity' => 'Обновить активность роли',
    'Update Activity' => 'Обновить активность',
    'User' => 'Пользователь',
    'Statistics' => 'Статистика',
    'My Statistics' => 'Моя статистика',
    'Working hours' => 'Рабочее время',
    'Edit comment' => 'Изменить комментарий',
    "You haven't started work yet!" => 'Вы еще не начали работу!',
    'The start of work has already been marked' => 'Начало работы уже проставлено',
    'Error setting the start of work' => 'Ошибка проставления начала работы',
    'Error setting the break' => 'Ошибка проставления перерыва',
    'Hint' => 'Подсказка',
    'Hints' => 'Подсказки',
    'Activity time' => 'Время активности',
    'Edit activity' => 'Редактировать активность',
    'Edit' => 'Изменить',
    'Table' => 'Таблица',
    'Chart' => 'Диаграмма',
    'Filter' => 'Фильтр',

    'Comment Templates' => 'Шаблоны комментариев',
    'Color' => 'Цвет',
    // actions
    'Save' => 'Сохранить',
    'Update' => 'Изменить',
    'Edit' => 'Редактировать',
    'Send' => 'Отправить',
    'Apply' => 'Применить',
    'Saving' => 'Сохранение',
    
    'Activity Properties' => 'Свойства активности',
    'Activity Property' => 'Свойство активности',
    'Create Activity Property' => 'Создать свойство активности',
    'Type' => 'Тип',
    'Integer' => 'Целое число',
    'String' => 'Строка',
    'Date' => 'Дата',
    'Time' => 'Время',
    'Checkbox' => 'Чекбокс',
    'Values' => 'Значения',
    'Position' => 'Позиция',
    'Update Activity Property' => 'Обновить свойство активности',
    'Error in setting the start date of work.' => 'Ошибка проставления начала работы',
    'Error when adding activity to a user.' => 'Ошибка при добавление активности пользователю',
    
    'Visibility conditions' => 'Условия видимости',
    'not equal' => 'не равно',
    'contains' => 'содержит',
    'Value' => 'Значение',
    
    'Username' => 'Логин',
    'Sex' => 'Пол',
    'Phone' => 'Телефон',
    'Required' => 'Обязательное для заполнения',
    'Yes' => 'Да',
    'No' => 'Нет',
    'Users' => 'Пользователи',
    'User Property' => 'Свойство пользователя',
    'Activities for which to display a property' => 'Активности, для которых отображать свойство',
    'Activities for which the property is required' => 'Активности, для которых свойство обязательно',
    
    'Dashboard' => 'Дашборд',
    'Duration' => 'Длительность',
    'Count' => 'Количество',
];
