<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Name' => 'Имя',
    'Title' => 'Название',
    'Comment' => 'Комментарий',
    'Start the working day' => 'Начать рабочий день',
    'Finish the working day' => 'Закончить рабочий день',
    'Break' => 'Перерыв',
    'Time Tracking' => 'Учет рабочего времени',
    'Time' => 'Время',
    'The start of the working day is marked' => 'Начало рабочего дня отмечено',
    'The end of the working day is marked' => 'Завершение рабочего дня отмечено',
    'Activity' => 'Активность',
    'The begining of the work day' => 'Начало рабочего дня',
    'End of the working day' => 'Завершение рабочего дня',
    'You have completed your working day.' => 'Вы завершили рабочий день.',
    'Add Activity' => 'Добавить активность',
    "You've already finished your work day!" => 'Вы уже закончили рабочий день!',
    'Role' => 'Роль',
    'Activities' => 'Активности',
    'Position' => 'Позиция',
    'Role Activities' => 'Активности ролей',
    'Add Activity for Role' => 'Добавить активность для роли',
    'Update Role Activity' => 'Обновить активность роли',
    'Update Activity' => 'Обновить активность',
    'User' => 'Пользователь',
    'Statistics' => 'Статистика',
    'My Statistics' => 'Моя статистика',
    'Edit comment' => 'Изменить комментарий',
    "You haven't started work yet!" => 'Вы еще не начали работу!',
    'The start of work has already been marked' => 'Начало работы уже проставлено',
    'Hint' => 'Подсказка',
    'Hints' => 'Подсказки',
    'Activity time' => 'Время активности',
    'Edit activity' => 'Редактировать активность',
    'Edit' => 'Изменить',

    'Comment Templates' => 'Шаблоны комментариев',
    'Color' => 'Цвет',
    // actions
    'Save' => 'Сохранить',
    'Update' => 'Изменить',
    'Edit' => 'Редактировать',
    'Send' => 'Отправить',
    'Apply' => 'Применить',
];
